export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAIL: "USERS_REGISTER_FAIL",
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAIL: "USERS_LOGIN_FAIL",
  LOGOUT: "USERS_LOGOUT",
  GET_REQUEST: "USERS_GET_REQUEST",
  GET_SUCCESS: "USERS_GET_SUCCESS",
  GET_FAIL: "USERS_GET_FAIL"
};
